apiVersion: oda.tmforum.org/v1beta2
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  componentId: TMFC019
  componentName: EventManagement
  componentFunctionalBlock: DecouplingAndIntegration 
  componenentDescription: "Event Management component is a messaging management component that is responsible for processing events as they happen from components. Processing of record of activities include modelling event messages, syntax validation and formatting of event messages and sending/receiving messages between components (consumer/producer). Event Management component supports different patterns of usage, including Event notification (subscription), Event-sourcing (representational state changes) and Event-carried state transfer (including data needed to perform further processing). Event Management component should include functionality providing a centralised CQRS queryStore for all components that implement event-sourcing with event carrier state transfer."
  componentVersion: 1.1.1
  componentStatus: specified 
  componentPublicationDate: 2023-08-18
  maintainers:
  - name: Gaetano Biancardi
    email: gaetano.biancardi@accenture.com
  owners:
  - name: Loen Peeters
    email: koen.peeters@ciminko.lu
coreFunction:
    exposedAPIs:
        - name: EventManagement
          id: TMF688
          isRequired: yes
          version: 4.0
          specification: https://raw.githubusercontent.com/tmforum-apis/TMF688-EventManagement/master/TMF688-EventManagement-v4.0.0.swagger.json
          implementation: /{{.Release.Name}}-EventManagement
          apitype: openapi
          path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/EventManagement/v4
          developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/EventManagement/v4/docs
          port: 8080
          resources:
          -  topic:
               - GET
               - POST
               - GET /id
               - PATCH /id
               - DELETE /id
          - topic/id/event:
               - POST
          - topic/id/queryStore:
               - GET
          - topic/id/hub:
               - GET
               - POST
               - GET /id
               - PATCH /id
               - DELETE /id
          - topic/id/importJob:
               - GET
               - POST
               - GET /id
               - PATCH /id
               - DELETE /id
          -  topic/id/exportJob:
               - GET
               - POST
               - GET /id
               - PATCH /id
               - DELETE /id
    dependantAPIs:
    - name: EventManagement 
      id: TMF688
      isRequired: no
      version: 4.0
      specification: https://github.com/tmforum-apis/TMF688-EventManagement/blob/master/TMF688-EventManagement-v4.0.0.swagger.json      
      apitype: openapi     
      resources: 
      - hub:
        - GET
        - POST                                  
        - GET /id
        - DELETE /id                                  
    publishedEvents: 
    - name: EventManagement
      specification: https://github.com/tmforum-apis/TMF688-EventManagement/blob/master/TMF688-EventManagement-v4.0.0.swagger.json      
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/EventManagement/call-back
      port: 80
      implementation: /{{.Release.Name}}-EventManagement
      apitype: openapi
      resources:   
      - EventManagement:
        - topicCreateEvent
        - TopicAttributeValueChangeEvent
        - TopicStateChangeEvent
        - TopicDeleteEvent
        - HubCreateEvent
        - HubAttributeValueChangeEvent
        - HubStateChangeEvent
        - HubDeleteEvent
    subscribedEvents: [] 
   
managementFunction: []
reportingFunction: []
securityFunction: []
